# site name
prefixName: Dexfire
siteName: ã®ã•ãã‚‰è˜ã
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /images/custom/avatar.jpg
url: https://dexfire.cn
description: çƒ­çˆ±æ˜¯æœ€ç»ˆçš„æ•‘èµï¼Œå‹‡æ•¢æ˜¯å”¯ä¸€çš„é€€è·¯~â¤
cdn: https://cdn.jsdelivr.net/gh/dexfire/cdn@v1.0.8
# cdn: ""
pjax: 1
sakura_widget:
# 0å…³é—­ 1å¼€å¯
mathjax: 0

signature:
  - æµè§ˆå™¨çœŸçš„å¾ˆçˆ±è®¡è¾ƒè‡ªå·±æ˜¯ä¸æ˜¯é»˜è®¤æµè§ˆå™¨ã€‚
  - çƒ­çˆ±æ˜¯æœ€ç»ˆçš„æ•‘èµï¼Œå‹‡æ•¢æ˜¯å”¯ä¸€çš„é€€è·¯~â¤
  - æ€»æ˜¯å¹æ°”ä¼šè®©å¹¸ç¦æ‚„æ‚„æºœèµ°å‚²~
  - ä»Šæ—¥é˜³å…‰ç…§å¸¸å‡èµ·ã€‚
  - å¯¹é…’å½“æ­Œï¼Œäººç”Ÿå‡ ä½•ã€‚
  - æˆ‘ä»¬å¾—å»åƒå–å«–èµŒï¼Œè€Œä¸æ˜¯åƒçˆ±æƒ…çš„è‹¦ã€‚
  - æ°¸è¿œè®¤æ¸…ç°å®ï¼Œä¹Ÿæ°¸è¿œç›¸ä¿¡ç«¥è¯ã€‚
  - éƒ½æ˜¯å–ADé’™é•¿å¤§ï¼Œå‡­ä»€ä¹ˆä»–ä»¬æ˜¯Aè€Œæˆ‘æ˜¯Dï¼Ÿ
  

notice: hexo-Sakuraä¸»é¢˜å·²ç»å¼€æºï¼Œæ¬¢è¿è®¿é—®...<a href="https://github.com/dexfire/hexo-theme-sakura"><img src="https://img.shields.io/badge/dexfire-hexo--theme--sakura?style=plastic&logo=git"/></a>
lazyloadImg: https://cdn.jsdelivr.net/gh/dexfire/cdn@v1.0/images/loader/orange.progress-bar-stripe-loader.svg

menus:
  ä¸»é¡µ: { path: /, fa: fa-fort-awesome faa-shake }
  æ—¶é—´çº¿: { path: /archives, fa: fa-archive faa-shake, submenus: {
    æŠ€æœ¯: {path: /categories/æŠ€æœ¯/, fa: fa-code },
    ç”Ÿæ´»: {path: /categories/ç”Ÿæ´»/, fa: fa-file-text-o },
    èµ„æº: {path: /categories/èµ„æº/, fa: fa-cloud-download },
    éšæƒ³: {path: /categories/éšæƒ³/, fa: fa-commenting-o },
    è½¬è½½: {path: /categories/è½¬è½½/, fa: fa-book }
  } }
  æ¸…å•: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: {
    ä¹¦å•: {path: /tags/æ‚¦è¯»/, fa: fa-th-list faa-bounce },
    ç•ªç»„: {path: /bangumi/, fa: fa-film faa-vertical },
    æ­Œå•: {path: /music/, fa: fa-headphones },
    å›¾é›†: {path: /tags/å›¾é›†/, fa: fa-photo }
  } }
  ç•™è¨€æ¿: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  å‹äººå¸: { path: /links/, fa: fa-link faa-shake }
  å’–å•¡: { path: /donate/, fa: fa-heart faa-pulse }
  å…³äº: { path: /, fa: fa-leaf faa-wrench , submenus: {
    æˆ‘: { path: /about/, fa: fa-meetup },
    ä¸»é¢˜: { path: /theme-sakura/, fa: iconfont icon-sakura },
    æ›´æ–°: { path: /theme-sakura/update_logs.html, fa: fa-ravelry },
    å®éªŒå®¤: { path: /lab/, fa: fa-cogs },
  } }
#  å®¢æˆ·ç«¯: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer firstï¼Œ1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# èƒŒæ™¯å›¾ç‰‡ æ›´å¥½çš„ä¿®æ”¹
bg:
  - https://cdn.jsdelivr.net/gh/dexfire/cdn/images/cover/IMG_0001.JPG
  - https://cdn.jsdelivr.net/gh/dexfire/cdn/images/cover/IMG_0002.JPG
  - https://cdn.jsdelivr.net/gh/dexfire/cdn/images/cover/IMG_7631.JPG
  - https://cdn.jsdelivr.net/gh/dexfire/cdn/images/cover/IMG_7632.JPG
  - https://cdn.jsdelivr.net/gh/dexfire/cdn/images/cover/IMG_7633.JPG
  - https://cdn.jsdelivr.net/gh/dexfire/cdn/images/cover/IMG_7634.JPG
  - https://cdn.jsdelivr.net/gh/dexfire/cdn/images/cover/IMG_7635.JPG
  - https://cdn.jsdelivr.net/gh/dexfire/cdn/images/cover/IMG_7636.JPG
  - https://cdn.jsdelivr.net/gh/dexfire/cdn/images/cover/IMG_7638.JPG
  - https://cdn.jsdelivr.net/gh/dexfire/cdn/images/cover/IMG_7639.JPG
  - https://cdn.jsdelivr.net/gh/dexfire/cdn/images/cover/IMG_7642.JPG
  - https://cdn.jsdelivr.net/gh/dexfire/cdn/images/cover/IMG_7643.jpg
  - https://cdn.jsdelivr.net/gh/dexfire/cdn/images/cover/IMG_7725.jpg
  - https://cdn.jsdelivr.net/gh/dexfire/cdn/images/cover/IMG_7760.jpg
  - https://dexfire.cn/img/20200614001.jpg

cdns:
  tocbot: //cdnjs.cloudflare.com/ajax/libs/tocbot/4.4.2/tocbot.min.js
  valine: //unpkg.com/valine/dist/Valine.min.js
  clipboard: //cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js
  busuanzi: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  aplayer: //cdn.jsdelivr.net/gh/moeplayer/hermit-x@2.9.6/assets/js/APlayer.min.js?ver=2.9.6
  aplayer_css: //cdn.jsdelivr.net/gh/moeplayer/hermit-x@2.9.6/assets/css/APlayer.min.css?ver=2.9.6
  font_awesome_css: //cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css

# èƒŒæ™¯å›¾ç‰‡æ ·å¼ ç©º åŸå›¾æ•ˆæœ filter-dim é˜´å½± filter-grid æ¨ªæ¡ filter-dot ç‚¹ç‚¹
bgclass: filter-dot

# startdash url, title, desc img
startdash:
  - {url: /theme-sakura/, title: Sakura, desc: æœ¬ç«™ hexo ä¸»é¢˜, img: /images/startdash/sakura.md.png}
  - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: åšä¸»çš„bç«™è§†é¢‘, img: /images/startdash/bilibili.jpg}
  - {url: /, title: dexfireã®åæ§½ä¹å›­, desc: æŠ€æœ¯æœåŠ¡, img: /images/startdash/wangshiwu.jpg}

post:
  - author: Dexfire
  - avatar: //q2.qlogo.cn/headimg_dl?dst_uin=1944404463&spec=5
  - authorLink: https://dexfire.cn
  - authorAbout: å¦‚æœè¿™ç¯‡æ–‡ç« å¯¹ä½ æœ‰å¸®åŠ©çš„è¯ï¼Œæ¬¢è¿ç•™ä¸ªğŸ‘£å—·~ãƒ¾(â‰§Oâ‰¦)ã€ƒ
  - authorDesc: çƒ­çˆ±æ˜¯æœ€ç»ˆçš„æ•‘èµï¼Œå‹‡æ•¢æ˜¯å”¯ä¸€çš„é€€è·¯~â¤

# ç»Ÿè®¡ç³»ç»Ÿï¼Œç›®å‰æ”¯æŒ Google analytics.js ç»Ÿè®¡ã€Google Tag Manager ç»Ÿè®¡ã€CNZZ ç»Ÿè®¡ã€è…¾è®¯ç»Ÿè®¡ã€51.Laç»Ÿè®¡ã€ç™¾åº¦ç»Ÿè®¡
analytics:
  google_site_id: #<ID>
  gtags_site_id: #<ID>
  cnzz_site_id: #<ID>
  tencent_site_id: #<ID>
  la_site_id: #<ID>
  baidu_site_id: 18d22dda3acd079101f04a6eacf3781e
  gtm_container_id: #<ID>

# your site build time or founded date
siteBuildingTime: 07/17/2018

#social  url, img PCç«¯é…ç½®
social:
  github: {url: http://github.com/honjun, img: /images/social/github.png}
  sina: {url: http://weibo.com/mashirozx?is_all=1, img: /images/social/sina.png}
  wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: /images/social/wangyiyun.png}
  zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /images/social/zhihu.png}
  email: {url: http://weibo.com/mashirozx?is_all=1, img: /images/social/email.svg}
  wechat: {url: /#, qrcode: /images/custom/wechat.jpg, img: /images/social/wechat.png}
  wechat2: {url: /#, qrcode: /images/custom/wechat.jpg, img: /images/social/wechat.png}

#social  url, img ç§»åŠ¨ç«¯é…ç½®
msocial:
  github: {url: http://github.com/honjun, fa: fa-github, color: 333}
  weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: https://www.paypal.me/hojuncn
  alipay: /images/custom/donate/AliPayQR.jpg
  wechat: /images/custom/donate/WeChanQR.jpg
  wechatSQ: /images/custom/donate/WeChanSQ.jpg

# è§†é¢‘åœ°å€ä¸ºhttps://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4ï¼Œé…ç½®å¦‚ä¸‹
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # å¤šä¸ªè§†é¢‘ç”¨é€—å·éš”å¼€ï¼Œéšæœºè·å–ã€‚æ”¯æŒçš„æ ¼å¼ç›®å‰å·²çŸ¥MP4,Flvã€‚å…¶ä»–çš„å¯ä»¥è¯•ä¸‹ï¼Œä¸ä¿è¯æœ‰ç”¨
  name: Unbroken.mp4

aplayer:
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: aFI53WTJYb4qPknwn0l76Lnu-gzGzoHsz
v_appKey: 2YeldrXS6Hm64JWCCLNgpj3C
